### ISSUE TITLE
Better erlangpl-ui provide method

### ISSUE THREAD

**Issue by baransu** [erlanglab/erlangpl#19]
Followup to: https://github.com/erlanglab/erlangpl/pull/18#issuecomment-288118042

Right now we have `erlangui-ui` submodule. It's not idea and we can do better.
Because UI is not a part of `erlangpl` codebase we should treat it as build dependency and create some kind of script to check UI version and update it automatically.

**Comment by arkgil** [comment]
What do you think about putting it all in one repository? We could manage issues with proper tagging.

**Comment by baransu** [comment]
@michalslaski what do you think?

**Comment by michalslaski** [comment]
I can see several advantages:

* easier versioning
* easier management of dependencies between UI and Erlang modules
* one repo to star and report issues

If it makes sense from building point of view, I'm all for it.

**Comment by baransu** [comment]
I'd go for it. I'll try to send relevant PR. One think may be hard, preserving UI commit history.

**Comment by ruanpienaar** [comment]
One repo would help, i was a dumbass on the weekend, and forgot to clone recursively, and then yarn had "package.json" missing issues. and then i carried on chasing my tail for nearly 20 mins :D

**Comment by baransu** [comment]
I'm going to merge both repos as fast as experimental UI plugin system will be merged into master.

I have [epl-plugin](https://github.com/Baransu/epl-plugin) running locally and there are only few changes I have to make. And a lot will come out when I'll be moving default plugins (dashboard, sup-tree, traffic) to new architecture.

**Comment by arkgil** [comment]
Great to hear that plugin system is almost ready!

**Comment by baransu** [comment]
There is a lot work to be done to have seamless plugin experience but core part is almost ready. I'll send PR to UI soon.

**Comment by baransu** [comment]
Resolved in https://github.com/erlanglab/erlangpl/pull/42
