### ISSUE TITLE
Update traffic data format

### ISSUE THREAD

**Issue by baransu** [erlanglab/erlangpl#24]
https://github.com/Netflix/vizceral/pull/59 got merged into Vizceral recently. It adds `entryNode` property and removes requirement for `INTERNET` node. It also allows two way message passing in our cluster view.

Things we have to change to update to version `4.4.0`:

* change `focused` -> `focusedChild`
* for every graph add `entryNode` property describing graph entry node 
* replace one, one way connection to entryNode with warnings with two, one way connection without it

**Comment by arkgil** [comment]
It is related into traffic view, right? I'll look into it as soon as I'm finished with Elixir stuff 🙂 

Does this update mean that there won't be INTERNET node, and we will have bi-directional particles flow?

**Comment by baransu** [comment]
Correct :)

**Comment by michalslaski** [comment]
Very cool.

BTW, in one of the Vizceral examples I saw force directed graph layout demo. Can we give it a try in the second level, where we render message passing?

**Comment by baransu** [comment]
I'll try to look into it.

**Comment by baransu** [comment]
@arkgil @michalslaski @mentels This change it crucial for us right now because a lot of people are trying EPL in recent days. These changes will fix no nodes in `/traffic` view when only one node in cluster. After getting this resolved on both front and backend we should release new version asap.

**Comment by arkgil** [comment]
I'll try to look into it this evening 🙂

**Comment by baransu** [comment]
@arkgil Are going to look into it today or can I?

**Comment by arkgil** [comment]
You can always look into issues, I'd be happy to help :) I don't have much time lately, sorry for delay.

EDIT: but I'm looking into it right now. Although extra pair of eyes does not harm anyone 😄
