### ISSUE TITLE
Get rid of `start_link` callback of plugin modules

### ISSUE THREAD

**Issue by arkgil** [erlanglab/erlangpl#26]
I have noticed that each plugin module needs to implement `start_link` callback, which for every plugin looks like this:
```erlang
start_link(_Options) ->
    {ok, spawn_link(fun() -> receive _ -> ok end end)}.
```

I was wondering if we really need this callback. If I checked correctly, the only place it is used is [here](https://github.com/erlanglab/erlangpl/blob/master/apps/epl/src/epl_app.erl#L192), which basically adds infinitely waiting child to `epl` supervisor.

I think we could remove this from all core plugins and of course remove the part which calls these functions. It could be a step towards creating friendlier plugin system 🙂 

While we're at it, in erlanglab/epl_counter#1 @michalslaski mentioned that `init` callback is also not used anymore, so maybe it's time to get rid of it too. Or at least rename it, so that it's not confused with `cowboy_websocket_handler` init callback.

**Comment by michalslaski** [comment]
Before we remove the init callback function, I would like to understand how EPL plugins will register in the new @Baransu 's UI plugin system.

**Comment by michalslaski** [comment]
I wanted some easy way to list all started plugins. Supervisor's which_children/1 seemed like what I wanted, but then Supervisors require Pid to be returned, so I hacked this start_link/1. I'm fine with removing it as long as we have a way to tell which plugins are started. One possible way is to list all subscribers to the epl_tracer, but I'm not sure all plugins will always want to subscribe to begin with.

**Comment by arkgil** [comment]
How about storing plugin names in additional ETS table?

**Comment by michalslaski** [comment]
Or assume that all started applications with their name prefixed with epl_* are plugins?

**Comment by baransu** [comment]
New plugins system will inject two lines per plugin into `<head>` tag in `index.html` served by server (`<script>` and `<link>` for JS and CSS). Also we will have to copy folder with static files (images, etc) into UI output build.

I'm doing this right now because I want option to include plugins into build without server. If the same plugin will be defined in some config file for `erlangpl` it we will replace builtin version.

EDIT: Every plugin will maintain own connection to `erlangpl` if specified route will be present.

**Comment by arkgil** [comment]
@michalslaski yes, we can assume that. It becomes related to #27. I know @mentels has some idea about imposing plugins being applications, but that's a subject for another issue.

**Comment by michalslaski** [comment]
After removing legacy UI callbacks, is there a way to preserve the debug printout `?INFO("Started plugins: ~p~n", [P])` ?

**Comment by arkgil** [comment]
Not at this point, if you're looking at the branch I've just created. However next PR I'll work on designing plugins as applications, so the log message will come back :)

**Comment by arkgil** [comment]
#38 resolved this issue, closing.
