### ISSUE TITLE
Crashdump when trying to connect to an Elixir or Erlang node

### ISSUE THREAD

**Issue by sashaafm** [erlanglab/erlangpl#30]
Hello, I just cloned your repo and followed your steps in order to get ErlangPL running and play with it. I've ran both an Elixir and Erlang emulator like so:

```
iex --name foo@127.0.0.1 -S mix
erl -name foo@127.0.0.1
```

and then
```
./erlangpl --node foo@127.0.0.1
```

and i got the following crash:

```
=INFO REPORT==== 4-Apr-2017::18:40:46 ===
    application: epl
    exited: {bad_return,
                {{epl_app,start,[normal,[]]},
                 {'EXIT',
                     {{badmatch,[]},
                      [{epl_app,insert_node_name,1,
                           [{file,"src/epl_app.erl"},{line,462}]},
                       {epl_app,start,2,[{file,"src/epl_app.erl"},{line,50}]},
                       {application_master,start_it_old,4,
                           [{file,"application_master.erl"},{line,273}]}]}}}}
    type: temporary
escript: exception error: no match of right hand side value
                 {error,
                     {bad_return,
                         {{epl_app,start,[normal,[]]},
                          {'EXIT',
                              {{badmatch,[]},
                               [{epl_app,insert_node_name,1,
                                    [{file,"src/epl_app.erl"},{line,462}]},
                                {epl_app,start,2,
                                    [{file,"src/epl_app.erl"},{line,50}]},
                                {application_master,start_it_old,4,
                                    [{file,"application_master.erl"},
                                     {line,273}]}]}}}}}
  in function  erlangpl:main/1 (src/erlangpl.erl, line 19)
  in call from escript:run/2 (escript.erl, line 760)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
```

I'm on Mac OS Sierra (latest) with Elixir 1.4.2 and Erlang/OTP 19 (erts-8.3). Am I missing anything? Thanks

**Comment by arkgil** [comment]
Can you try running `erlangpl` with `-vvv` flag? I can't reproduce your issue (on the exact same OS), so additional debug logs might help us :)

**Comment by arkgil** [comment]
Okay, I see what might a problem. Please ensure that you have run `make build-ui` before `make` itself. We should probably fail with a more friendly message if we can't find UI files at runtime.

**Comment by arkgil** [comment]
@sashaafm let me know if that solves your issue 🙂

**Comment by sashaafm** [comment]
@arkgil yes that fixed it. Checking out erlangpl right now. However, I had to clone the repo again, it seems trying to `build-ui` after make and then make again does not work. I believe the guide in the website is missing the `build-ui` step.

Also I had to install Elm, so I think a guide with the needed dependencies would be a good addition.

**Comment by arkgil** [comment]
Dependencies are listed in the README, although it's definitely not clear enough. Thank for the feedback!

**Comment by baransu** [comment]
We're working on UI plugin system and with that Elm dependency will be removed. We wont use it in our core code but you will be able to write plugins in Elm.
