### ISSUE TITLE
Cluster traffic view not rendering

### ISSUE THREAD

**Issue by cdesch** [erlanglab/erlangpl#40]
I was playing with Phoenix and ErlangPL in this [video](https://www.youtube.com/watch?v=aUCwtG_rr34) and could not get the traffic on the cluster to render. I also tried following the mensia sample in the readme with no luck. How do I troubleshoot or debug this issue?

![screen shot 2017-04-07 at 10 36 07 am](https://cloud.githubusercontent.com/assets/1207795/24805024/5a55ee34-1b7e-11e7-88df-084c9d52b5b1.png)

**Comment by baransu** [comment]
This issue is related to underlaying tool.
It was already reported here https://github.com/erlanglab/erlangpl-ui/issues/29. We have PR https://github.com/erlanglab/erlangpl/pull/39 in progress fixing this bug.

**Comment by baransu** [comment]
Should be fixed right now, thanks to #39 and https://github.com/erlanglab/erlangpl-ui/pull/31.

**Comment by cdesch** [comment]
This issue hasn't been fixed. Is this rated for a specific version of elixir or erlang? [Video](https://youtu.be/LtczIYIAPIA)

elixir version:

```
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.2
```
```
cjs-MBP15:erlangpl cj$  erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell
"19"
```

**Comment by arkgil** [comment]
Hm, it's really strange. It should be working with the newest version, and is indeed working for me. Could you please paste here how did you start the nodes and what examples did you run? Also the logs from the browser. I know it's all in the video, but I think that written explanation here would be easier for us to comment 🙂  Sorry for trouble!

**Comment by cdesch** [comment]
@arkgil It is working. Thanks! I pulled the latest version but I needed to recompile the assets for it to work

It seems like this

```
$ make ui
$ make
$ ./bootstrap
```
process needs to be rerun after every code pull if you're (myself) are not monitoring the change diff between commits.

Minor Housekeeping note for others troubleshooting. :-)
