### ISSUE TITLE
OTP 20 + old cowboy + crypto

### ISSUE THREAD

**Issue by gomoripeti** [erlanglab/erlangpl#58]
In OTP 20 functions deprecated in crypto-3.0 first released in OTP-R16B01 will be removed.

The currently used cowboy version 0.8.6 uses `crypto:sha` in websocket which won't work from OTP 20.

**Comment by arkgil** [comment]
Thanks for raising this issue @gomoripeti! 🙂  This is something on top of our priority list right now, stay tuned 👍
