### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by tckb** [erlanglab/erlangpl#91]
@michalslaski  @mkacper  is this project still alive?  As a beginner in erlang/elixir this is _the_  project I was searching for visualizing stuff going on in my app.  I had the same issue as #89   is there any way to fix this issue?

**Comment by michalslaski** [comment]
@tckb at present we use this tool for educational purposes during trainings and meetups, so you may say that the project is alive :)

In systems with many processes sending messages the visualisation is unreadable and we don't have a fix for this. The other problem of processes disappearing and appearing again can be fixed. I'm not working on a fix at the moment, but I'm glad you shared your feedback. It gives motivation to revisit this issue and improve the tool.

**Comment by tckb** [comment]
thanks for the reaffirmation @michalslaski  .  my main usecase for this project would be a "demo" for my colleagues and _visualizing_  message passing  between processes would a great start!  If it's a trivial fix then may be I could help.
